"""Static nickname/diminutive lookup for first-name matching.

Maps common English nicknames to a shared canonical form so that
e.g. "Tim" and "Timothy" are recognized as the same first name.
"""

from __future__ import annotations

from typing import Final

_RAW_GROUPS: Final[dict[str, list[str]]] = {
    "alexander": ["alex", "xander", "sasha"],
    "alexandra": ["alex", "alexa", "lexi", "sandra"],
    "alfred": ["al", "alf", "alfie", "fred"],
    "andrew": ["andy", "drew"],
    "anthony": ["tony", "ant"],
    "arthur": ["art", "artie"],
    "barbara": ["barb", "barbie", "babs"],
    "benjamin": ["ben", "benji", "benny"],
    "catherine": ["cathy", "cath", "cat", "kate", "katie", "kitty"],
    "charles": ["charlie", "chuck", "chas"],
    "charlotte": ["charlie", "lottie", "char"],
    "christopher": ["chris", "topher", "kit"],
    "christine": ["chris", "christy", "tina"],
    "clarence": ["clare"],
    "clifford": ["cliff"],
    "constance": ["connie"],
    "cynthia": ["cindy"],
    "daniel": ["dan", "danny"],
    "david": ["dave", "davey"],
    "deborah": ["deb", "debbie"],
    "dennis": ["denny"],
    "diana": ["di"],
    "dolores": ["dolly", "lola"],
    "donald": ["don", "donny"],
    "dorothy": ["dot", "dotty", "dottie"],
    "douglas": ["doug"],
    "edward": ["ed", "eddie", "ted", "teddy", "ned"],
    "eleanor": ["ellie", "ella", "nora"],
    "elizabeth": ["liz", "lizzy", "beth", "betty", "betsy", "eliza", "ellie", "libby", "bess", "bessie"],
    "emily": ["em", "emmy"],
    "eugene": ["gene"],
    "florence": ["flo", "flossie"],
    "frances": ["fran", "frankie", "franny"],
    "francis": ["frank", "frankie"],
    "frederick": ["fred", "freddy", "freddie", "fritz"],
    "gabriel": ["gabe"],
    "geoffrey": ["geoff", "jeff"],
    "george": ["georgie"],
    "gerald": ["gerry", "jerry"],
    "gertrude": ["gert", "gertie", "trudy"],
    "gregory": ["greg"],
    "harold": ["hal", "harry"],
    "harrison": ["harry"],
    "harriet": ["hattie"],
    "henry": ["hank", "harry", "hal"],
    "howard": ["howie"],
    "irene": ["rene"],
    "jacob": ["jake", "jack"],
    "jacqueline": ["jackie", "jacqui"],
    "james": ["jim", "jimmy", "jamie", "jem"],
    "janet": ["jan"],
    "jason": ["jay"],
    "jean": ["jeanie"],
    "jennifer": ["jen", "jenny", "jenn"],
    "jerome": ["jerry"],
    "jessica": ["jess", "jessie"],
    "joanna": ["jo", "joanie"],
    "john": ["jack", "johnny", "jon"],
    "jonathan": ["jon", "jonny", "nathan"],
    "joseph": ["joe", "joey"],
    "joshua": ["josh"],
    "judith": ["judy", "judi"],
    "katherine": ["kate", "kathy", "kat", "katie", "kitty", "kay"],
    "kathleen": ["kathy", "kate", "katie", "kay"],
    "kenneth": ["ken", "kenny"],
    "kimberly": ["kim", "kimmy"],
    "laurence": ["larry", "laurie"],
    "leonard": ["leo", "len", "lenny"],
    "leopold": ["leo"],
    "lillian": ["lily", "lil"],
    "linda": ["lindy"],
    "louis": ["lou", "louie"],
    "louise": ["lou"],
    "lucas": ["luke"],
    "lucille": ["lucy", "lu"],
    "madeline": ["maddie", "maddy"],
    "margaret": ["maggie", "meg", "peggy", "marge", "margie", "rita"],
    "martha": ["marty", "mattie"],
    "martin": ["marty"],
    "mary": ["molly", "polly", "mae"],
    "matthew": ["matt", "matty"],
    "maureen": ["mo"],
    "maximilian": ["max"],
    "melanie": ["mel"],
    "melissa": ["mel", "missy"],
    "michael": ["mike", "mikey", "mick", "mickey"],
    "michelle": ["shelly", "micki"],
    "mildred": ["millie", "milly"],
    "mitchell": ["mitch"],
    "nancy": ["nan"],
    "natalie": ["nat"],
    "nathan": ["nate"],
    "nathaniel": ["nate", "nat"],
    "nicholas": ["nick", "nicky"],
    "nicole": ["nicky", "nikki"],
    "oliver": ["ollie"],
    "patricia": ["pat", "patty", "trish", "tricia"],
    "patrick": ["pat", "paddy"],
    "paul": ["paulie"],
    "penelope": ["penny"],
    "peter": ["pete"],
    "philip": ["phil"],
    "priscilla": ["prissy", "cilla"],
    "rachel": ["rach"],
    "randolph": ["randy"],
    "raymond": ["ray"],
    "rebecca": ["becky", "becca", "bex"],
    "regina": ["gina"],
    "reginald": ["reg", "reggie"],
    "richard": ["rick", "ricky", "rich", "dick", "richie"],
    "robert": ["rob", "robbie", "bob", "bobby", "bert", "robby"],
    "roderick": ["rod", "roddy"],
    "roger": ["rog"],
    "ronald": ["ron", "ronnie"],
    "rosalind": ["ros", "roz"],
    "rosemary": ["rosie"],
    "russell": ["russ", "rusty"],
    "ruth": ["ruthie"],
    "samantha": ["sam", "sammy"],
    "samuel": ["sam", "sammy"],
    "sandra": ["sandy"],
    "sarah": ["sally", "sadie"],
    "sebastian": ["seb"],
    "sharon": ["shari"],
    "sophia": ["sophie"],
    "stanley": ["stan"],
    "stephanie": ["steph", "stevie"],
    "stephen": ["steve", "stevie"],
    "steven": ["steve", "stevie"],
    "stuart": ["stu"],
    "susan": ["sue", "suzy", "susie"],
    "suzanne": ["sue", "suzy"],
    "sylvia": ["syl"],
    "teresa": ["terry", "tess", "tessa"],
    "theodore": ["ted", "teddy", "theo"],
    "thomas": ["tom", "tommy"],
    "timothy": ["tim", "timmy"],
    "tobias": ["toby"],
    "valerie": ["val"],
    "veronica": ["ronnie", "roni"],
    "victor": ["vic", "vicky"],
    "victoria": ["vicky", "tori"],
    "vincent": ["vince", "vinny"],
    "virginia": ["ginny", "ginger"],
    "vivian": ["viv"],
    "walter": ["walt", "wally"],
    "wendy": ["wen"],
    "william": ["will", "willy", "bill", "billy", "liam"],
    "zachary": ["zach", "zack"],
}

_CANONICAL: dict[str, str] = {}

for _canonical, _nicknames in _RAW_GROUPS.items():
    _CANONICAL[_canonical] = _canonical
    for _nick in _nicknames:
        if _nick not in _CANONICAL:
            _CANONICAL[_nick] = _canonical


def _resolve(name: str) -> str:
    """Return the canonical form for a first name, or the lowered input itself."""
    lowered: str = name.strip().lower()
    return _CANONICAL.get(lowered, lowered)


def first_names_match(a: str, b: str) -> bool:
    """Return True if two first names are the same or known nickname variants."""
    if not a or not b:
        return False
    return _resolve(a) == _resolve(b)
